<?php

class MeuFiltro extends php_user_filter
{
    public function onCreate()
    {
        parent::onCreate(); // TODO: Change the autogenerated stub
    }
    public function filter($in, $out, &$consumed, $closing)
    {
        parent::filter($in, $out, $consumed, $closing); // TODO: Change the autogenerated stub
    }
}